name: gfgcustomfonts
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.8.0 

flutter_icons:
  android: 'launcher_icon'  
  ios: true
  image_path: 'assets/icon/rc.png'


flutter:
  uses-material-design: true
fonts:
 - family: LuxuriousRoman
   fonts:
   - asset: fonts/LuxuriousRoman-Regular.ttf
